spring.application.name=api-gateway

server.port = 8888



#spring.cloud.gateway.routes[0].id = test
#spring.cloud.gateway.routes[0].uri = http://localhost:8081
#spring.cloud.gateway.routes[0].predicates[0] = Path=/users/**
#
#management.endpoints.web.exposure.include=*


eureka.client.serviceUrl.defaultZone = http://localhost:8761/registry/eureka



#enable dynamic routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true